// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsFuL9NSIpuwVO9zyh66f6CRz_MRKW6I',
    appId: '1:150199405061:web:33957111577a037b30aa6c',
    messagingSenderId: '150199405061',
    projectId: 'first-project-5720f',
    authDomain: 'first-project-5720f.firebaseapp.com',
    storageBucket: 'first-project-5720f.firebasestorage.app',
    measurementId: 'G-DN6WZ481WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCixlld6nX_Q3sS9KyEw6U6tgJVys2SCJo',
    appId: '1:150199405061:android:e06478ee679f5cb630aa6c',
    messagingSenderId: '150199405061',
    projectId: 'first-project-5720f',
    storageBucket: 'first-project-5720f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kb2klDBSQsSxPYx_Abc5YGccjPHgJ-g',
    appId: '1:150199405061:ios:efd38338ec5bd70830aa6c',
    messagingSenderId: '150199405061',
    projectId: 'first-project-5720f',
    storageBucket: 'first-project-5720f.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );
}
